### ISSUE TITLE
Subprocess failed on (first & subsequent) running of 'lein ring server'

### ISSUE THREAD

**Issue by dan-mi-sun** [Commonfare-net/macao-social-wallet#83]
Hey folks,

Having some issues with installation. This is quite likely the fact I am unfamiliar with clojure.

After running through the installation instructions here: https://github.com/Commonfare-net/macao-social-wallet

I first made sure that mongo was running:

```
[  3:38am ]  [ user@host:~/Lib/macao-social-wallet(master✔) ]
 $ ps aux | grep "mongo"
user      2537  0.0  0.0  12728  2060 pts/0    S+   03:39   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn mongo
mongodb  28670  0.3  0.2 387484 45776 ?        Sl   02:52   0:09 /usr/bin/mongod --config /etc/mongodb.conf
```

I am getting the following error stacktrace when firing up the server:

```
[  3:39am ]  [ user@host:~/Lib/macao-social-wallet(master✔) ]
 $ lein ring server     
(Warning: profile :dev-local not found.)
Possibly confusing dependencies found:
[ring/ring-core "1.6.2"] -> [clj-time "0.11.0"]
 overrides
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [clojure-humanize "0.2.2"] -> [clj-time "0.12.0"]
 and
[clojure-humanize "0.2.2"] -> [clj-time "0.12.0"]

Consider using these exclusions:
[org.clojars.dyne/freecoin-lib "0.8.0" :exclusions [clj-time]]
[clojure-humanize "0.2.2" :exclusions [clj-time]]

[circleci/clj-yaml "0.5.6"] -> [org.yaml/snakeyaml "1.13"]
 overrides
[org.clojars.dyne/just-auth "0.1.0"] -> [org.clojars.dyne/auxiliary "0.4.0"] -> [io.forward/yaml "1.0.6"] -> [org.yaml/snakeyaml "1.18"]
 and
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [org.clojars.dyne/auxiliary "0.4.0"] -> [io.forward/yaml "1.0.6"] -> [org.yaml/snakeyaml "1.18"]
 and
[org.clojars.dyne/auxiliary "0.4.0"] -> [io.forward/yaml "1.0.6"] -> [org.yaml/snakeyaml "1.18"]

Consider using these exclusions:
[org.clojars.dyne/just-auth "0.1.0" :exclusions [org.yaml/snakeyaml]]
[org.clojars.dyne/freecoin-lib "0.8.0" :exclusions [org.yaml/snakeyaml]]
[org.clojars.dyne/auxiliary "0.4.0" :exclusions [org.yaml/snakeyaml]]

[org.clojars.dyne/freecoin-lib "0.8.0"] -> [prismatic/schema "1.1.6"]
 overrides
[org.clojars.dyne/just-auth "0.1.0"] -> [prismatic/schema "1.1.7"]

Consider using these exclusions:
[org.clojars.dyne/just-auth "0.1.0" :exclusions [prismatic/schema]]

[midje "1.8.3"] -> [org.clojure/tools.namespace "0.2.10"]
 overrides
[ns-tracker "0.3.1"] -> [org.clojure/tools.namespace "0.2.11"]

Consider using these exclusions:
[ns-tracker "0.3.1" :exclusions [org.clojure/tools.namespace]]

[ring/ring-core "1.6.2"] -> [clj-time "0.11.0"] -> [joda-time "2.8.2"]
 overrides
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [clojure-humanize "0.2.2"] -> [clj-time "0.12.0"] -> [joda-time "2.9.3"]
 and
[clojure-humanize "0.2.2"] -> [clj-time "0.12.0"] -> [joda-time "2.9.3"]

Consider using these exclusions:
[org.clojars.dyne/freecoin-lib "0.8.0" :exclusions [joda-time]]
[clojure-humanize "0.2.2" :exclusions [joda-time]]

[scenic "0.2.5"] -> [bidi "1.11.0"] -> [org.clojure/clojurescript "0.0-2371"] -> [org.clojure/tools.reader "0.8.9"]
 overrides
[org.clojars.dyne/just-auth "0.1.0"] -> [org.clojars.dyne/auxiliary "0.4.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]
 and
[org.clojars.dyne/just-auth "0.1.0"] -> [org.clojars.dyne/clj-storage "0.5.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]
 and
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [org.clojars.dyne/auxiliary "0.4.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]
 and
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [org.clojars.dyne/clj-storage "0.5.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]
 and
[org.clojars.dyne/auxiliary "0.4.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]
 and
[org.clojars.dyne/just-auth "0.1.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]
 and
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [com.taoensso/timbre "4.10.0"] -> [com.taoensso/encore "2.91.0"] -> [org.clojure/tools.reader "0.10.0"]

Consider using these exclusions:
[org.clojars.dyne/just-auth "0.1.0" :exclusions [org.clojure/tools.reader]]
[org.clojars.dyne/freecoin-lib "0.8.0" :exclusions [org.clojure/tools.reader]]
[org.clojars.dyne/auxiliary "0.4.0" :exclusions [org.clojure/tools.reader]]

[ring.middleware.logger "0.5.0" :exclusions [org.slf4j/slf4j-api]] -> [onelog "0.4.5"] -> [clj-logging-config "1.9.10"] -> [log4j "1.2.16"]
 overrides
[ring.middleware.logger "0.5.0" :exclusions [org.slf4j/slf4j-api]] -> [onelog "0.4.5"] -> [org.slf4j/slf4j-log4j12 "1.7.7"] -> [log4j "1.2.17"]

Consider using these exclusions:
[ring.middleware.logger "0.5.0" :exclusions [log4j org.slf4j/slf4j-api]]

[scenic "0.2.5"] -> [bidi "1.11.0"] -> [org.clojure/clojurescript "0.0-2371"] -> [com.google.javascript/closure-compiler "v20140625"] -> [com.google.guava/guava "17.0"]
 overrides
[org.clojars.dyne/just-auth "0.1.0"] -> [org.clojars.dyne/clj-storage "0.5.0"] -> [com.novemberain/monger "3.1.0"] -> [clojurewerkz/support "1.1.0"] -> [com.google.guava/guava "18.0"]
 and
[org.clojars.dyne/freecoin-lib "0.8.0"] -> [org.clojars.dyne/clj-storage "0.5.0"] -> [com.novemberain/monger "3.1.0"] -> [clojurewerkz/support "1.1.0"] -> [com.google.guava/guava "18.0"]

Consider using these exclusions:
[org.clojars.dyne/just-auth "0.1.0" :exclusions [com.google.guava/guava]]
[org.clojars.dyne/freecoin-lib "0.8.0" :exclusions [com.google.guava/guava]]

"lein-ring-init"
Jan 19, 2018 3:41:35 AM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
Exception in thread "main" java.io.FileNotFoundException: email-conf.edn (No such file or directory), compiling:(/tmp/form-init7994703934240977116.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: email-conf.edn (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at clojure.java.io$fn__9520.invokeStatic(io.clj:229)
	at clojure.java.io$fn__9520.invoke(io.clj:229)
	at clojure.java.io$fn__9433$G__9426__9440.invoke(io.clj:69)
	at clojure.java.io$fn__9532.invokeStatic(io.clj:258)
	at clojure.java.io$fn__9532.invoke(io.clj:254)
	at clojure.java.io$fn__9433$G__9426__9440.invoke(io.clj:69)
	at clojure.java.io$fn__9494.invokeStatic(io.clj:165)
	at clojure.java.io$fn__9494.invoke(io.clj:165)
	at clojure.java.io$fn__9446$G__9422__9453.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$slurp.invokeStatic(core.clj:6657)
	at clojure.core$slurp.doInvoke(core.clj:6657)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at freecoin.core$lein_ring_init$fn__22030.invoke(core.clj:230)
	at clojure.lang.Atom.swap(Atom.java:37)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2260)
	at clojure.core$swap_BANG_.invoke(core.clj:2253)
	at freecoin.core$lein_ring_init.invokeStatic(core.clj:227)
	at freecoin.core$lein_ring_init.invoke(core.clj:223)
	at clojure.lang.Var.invoke(Var.java:375)
	at ring.server.standalone$serve.invokeStatic(standalone.clj:95)
	at ring.server.standalone$serve.doInvoke(standalone.clj:75)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at ring.server.leiningen$serve.invokeStatic(leiningen.clj:13)
	at ring.server.leiningen$serve.invoke(leiningen.clj:10)
	at user$eval22034.invokeStatic(form-init7994703934240977116.clj:1)
	at user$eval22034.invoke(form-init7994703934240977116.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed
```

If it is useful I am running devuan.org

```
$ uname -a
Linux host 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by dan-mi-sun** [comment]
Seem to have gotten past that with a simple

`touch email-conf.edn` in root of project

**Comment by aspasia** [comment]
thanks for pointing out @dan-mi-sun. A configuration is needed in order to be able to send email con firmations when users sign up, reset their password etc. The conf file should look like 
`{:email-server ""
 :email-user ""
 :email-pass ""
 :email-address ""}`
I will add it to the README file

**Comment by jaromil** [comment]
hey Dan !! BTW have a look also at the REST API (social-wallet-api) ;^)

**Comment by dan-mi-sun** [comment]
@jaromil hi! 

doing so now, much excite!!

**Comment by KGibb8** [comment]
Thanks, same issue resolved, this was helpful! 👍  😄

**Comment by dan-mi-sun** [comment]
@jaromil @aspasia , please both meet my friend and colleague @KGibb8 . We're working on a project at the moment and exploring freecoin as a foundation tech... We'll likely be in touch with you over the coming months.

<3

**Comment by KGibb8** [comment]
Hi all!

**Comment by aspasia** [comment]
Awesome @KGibb8 @dan-mi-sun !!! Looking forward to hearing more about your projects, please let me know when oyu wanna have a chat!
